# Tests generated by: guppy.gsl.Tester
# Main source file: /home/zhuyifei1999/guppy3/specs/genguppy.gsl
# Date: Fri Aug 16 10:54:19 2019
class Tester:
    tests = {}
    def test_guppy(self, arg):
        t0 = arg.Root()
        t1 = arg.hpy()
        t2 = arg.hpy(ht=())
    tests['.tgt.kindnames.guppy'] = test_guppy
