# Tests generated by: guppy.gsl.Tester
# Main source file: /home/zhuyifei1999/guppy3/specs/genguppy.gsl
# Date: Fri Aug 16 10:54:19 2019
class Tester:
    tests = {}
    def get_ex_1(self):
        class C:
            pass
        return C
    def get_ex_2(self):
        class C:
            pass
        return C
    def get_ex_3(self):
        class C:
            pass
        return C
    def get_ex_4(self):
        import sys
        return id(sys)
    def get_ex_5(self):
        class C:
         pass
        return self.hp.Clodo(dictof=C)
    def get_ex_6(self):
        import os
        return os.path.join(os.path.dirname(__file__),'profileexample.hpy')
    def get_ex_7(self):
        import os
        return open(os.path.join(os.path.dirname(__file__),'profileexample.hpy'))
    def get_ex_8(self):
        import os
        return os.path.join(os.path.dirname(__file__),'profileexample.hpy')
    def test_Use(self, arg):
        t0 = arg.Size(0)
        t1 = arg.Root
        t2 = arg.Rcs()
        t3 = arg.Rcs(self.get_ex_5())
        t4 = arg.Rcs(self.hp.Clodo.sokind(int)(dictof=()))
        t5 = arg.Module()
        t6 = arg.Module(name='sys')
        t7 = arg.Module(at=self.get_ex_4())
        t8 = arg.Module(name='sys', at=self.get_ex_4())
        t9 = arg.Unity()
        t10 = arg.Clodo(int)
        t11 = arg.Clodo(self.get_ex_2())
        t12 = arg.Clodo(dictof=())
        t13 = arg.Clodo(dictof=self.get_ex_3())
        t14 = arg.Id(id(None))
        t15 = arg.Class(int)
        t16 = arg.Class(self.get_ex_1())
        t17 = arg.Nothing
        t18 = arg.Anything
        t19 = arg.heapu()
        t20 = arg.load(self.get_ex_6())
        t21 = arg.load(self.get_ex_7())
        t22 = arg.load(self.get_ex_6(), use_readline=True)
        t23 = arg.load(self.get_ex_7(), use_readline=True)
        t24 = arg.heap()
        t25 = arg.heapg()
        t26 = arg.idset([1])
        t27 = arg.iso()
        t28 = arg.iso(())
        t29 = arg.findex()
        t30 = t29(0)
        t31 = arg.findex(self.hp.Anything)
        t32 = t31(0)
        t33 = arg.Via()
        t34 = arg.Via('[0]')
        t35 = arg.Via('.a')
        t36 = arg.Type(int)
        t37 = arg.doc
        t38 = arg.monitor()
        t39 = arg.pb()
        t40 = arg.pb(self.get_ex_8())
        t41 = arg.setref()
        t42 = arg.setrelheap()
        t43 = arg.setrelheap(self.hp.Nothing)
        t44 = arg.setrelheapg()
        t45 = arg.setrelheapg(self.hp.Nothing)
        t46 = arg.setrelheapu()
        t47 = arg.setrelheapu(self.hp.Nothing)
    tests['.tgt.heapykinds.Use'] = test_Use
