# Tests generated by: guppy.gsl.Tester
# Date: Sat Aug 17 13:29:53 2019
class Tester:
    tests = {}
    def test_guppy(self, arg):
        t0 = arg.Root()
        t1 = arg.hpy()
        t2 = arg.hpy(ht=())
    tests['.tgt.kindnames.guppy'] = test_guppy
